// Pakistan Provinces
export const pakistanProvinces = [
  'Punjab',
  'Sindh',
  'Khyber Pakhtunkhwa',
  'Balochistan',
  'Gilgit-Baltistan',
  'Azad Jammu and Kashmir',
  'Islamabad Capital Territory',
]

// Major Cities of Pakistan (unique list)
export const pakistanCities = [
  // Punjab
  'Lahore',
  'Faisalabad',
  'Rawalpindi',
  'Multan',
  'Gujranwala',
  'Sialkot',
  'Bahawalpur',
  'Sargodha',
  'Sheikhupura',
  'Jhang',
  'Dera Ghazi Khan',
  'Gujrat',
  'Sahiwal',
  'Wah Cantonment',
  'Kasur',
  'Okara',
  'Chiniot',
  'Kamoke',
  'Hafizabad',
  'Sadiqabad',
  'Burewala',
  'Khanewal',
  'Muzaffargarh',
  'Mandi Bahauddin',
  'Gojra',
  'Bahawalnagar',
  'Samundri',
  'Jaranwala',
  'Chishtian',
  'Attock',
  'Mianwali',
  'Kot Addu',
  'Vihari',
  'Narowal',
  'Pakpattan',
  'Rahim Yar Khan',
  'Chakwal',
  'Khushab',
  'Daska',
  'Mian Channu',
  'Bhakkar',
  'Lodhran',
  'Ahmedpur East',
  'Kotri',
  'Toba Tek Singh',
  'Jhelum',
  'Haroonabad',
  'Shakargarh',
  'Nankana Sahib',
  'Haveli Lakha',
  'Chichawatni',
  'Kabirwala',
  'Hasilpur',
  'Arifwala',
  'Gujar Khan',
  'Muridke',
  'Mianwali',
  'Bhalwal',
  'Layyah',
  'Kotli',
  'Tandlianwala',
  'Ferozewala',
  'Chak Jhumra',
  'Renala Khurd',
  'Lala Musa',
  'Kharian',
  'Ahmadpur Sial',
  'Pindi Bhattian',
  'Jatoi',
  'Dunyapur',
  'Dipalpur',
  'Naushahro Feroze',
  'Chenab Nagar',
  'Pasrur',
  'Sambrial',
  'Shujaabad',
  'Hujra Shah Muqim',
  'Kabirwala',
  'Mananwala',
  'Hafizabad',
  'Kot Radha Kishan',
  'Warburton',
  'Dera Ismail Khan',
  'Chakwal',
  'Mianwali',
  'Bhakkar',
  'Khushab',
  'Layyah',
  'Bhalwal',
  'Kot Addu',
  'Muzaffargarh',
  'Jhang',
  'Sahiwal',
  'Okara',
  'Pakpattan',
  'Chichawatni',
  'Arifwala',
  'Gojra',
  'Kamalia',
  'Hafizabad',
  'Wazirabad',
  'Gujrat',
  'Sialkot',
  'Daska',
  'Pasrur',
  'Narowal',
  'Shakargarh',
  'Gujranwala',
  'Sialkot',
  'Gujrat',
  'Wazirabad',
  'Daska',
  'Pasrur',
  'Narowal',
  'Shakargarh',
  'Sheikhupura',
  'Nankana Sahib',
  'Ferozewala',
  'Muridke',
  'Lahore',
  'Kasur',
  'Okara',
  'Pakpattan',
  'Chichawatni',
  'Arifwala',
  'Gojra',
  'Kamalia',
  'Hafizabad',
  'Wazirabad',
  'Gujrat',
  'Sialkot',
  'Daska',
  'Pasrur',
  'Narowal',
  'Shakargarh',
  'Gujranwala',
  'Sialkot',
  'Gujrat',
  'Wazirabad',
  'Daska',
  'Pasrur',
  'Narowal',
  'Shakargarh',
  'Sheikhupura',
  'Nankana Sahib',
  'Ferozewala',
  'Muridke',
  'Lahore',
  'Kasur',
  'Okara',
  'Pakpattan',
  'Chichawatni',
  'Arifwala',
  'Gojra',
  'Kamalia',
  'Hafizabad',
  'Wazirabad',
  'Gujrat',
  'Sialkot',
  'Daska',
  'Pasrur',
  'Narowal',
  'Shakargarh',
  'Gujranwala',
  'Sialkot',
  'Gujrat',
  'Wazirabad',
  'Daska',
  'Pasrur',
  'Narowal',
  'Shakargarh',
  'Sheikhupura',
  'Nankana Sahib',
  'Ferozewala',
  'Muridke',
  // Sindh
  'Karachi',
  'Hyderabad',
  'Sukkur',
  'Larkana',
  'Nawabshah',
  'Mirpur Khas',
  'Jacobabad',
  'Shikarpur',
  'Khairpur',
  'Dadu',
  'Tando Allahyar',
  'Tando Adam',
  'Badin',
  'Thatta',
  'Matiari',
  'Hala',
  'Tando Muhammad Khan',
  'Umerkot',
  'Sanghar',
  'Naushahro Feroze',
  'Shaheed Benazirabad',
  'Jamshoro',
  'Sehwan',
  'Larkana',
  'Shikarpur',
  'Jacobabad',
  'Kashmore',
  'Ghotki',
  'Sukkur',
  'Khairpur',
  'Nawabshah',
  'Sanghar',
  'Mirpur Khas',
  'Umerkot',
  'Tharparkar',
  'Matiari',
  'Tando Allahyar',
  'Tando Adam',
  'Hala',
  'Tando Muhammad Khan',
  'Badin',
  'Thatta',
  'Sujawal',
  'Karachi East',
  'Karachi West',
  'Karachi South',
  'Karachi Central',
  'Malir',
  'Korangi',
  // Khyber Pakhtunkhwa
  'Peshawar',
  'Mardan',
  'Mingora',
  'Kohat',
  'Abbottabad',
  'Dera Ismail Khan',
  'Charsadda',
  'Nowshera',
  'Swabi',
  'Bannu',
  'Haripur',
  'Mansehra',
  'Timergara',
  'Tank',
  'Lakki Marwat',
  'Dera Ismail Khan',
  'Bannu',
  'Kohat',
  'Hangu',
  'Karak',
  'Buner',
  'Shangla',
  'Swat',
  'Dir',
  'Chitral',
  'Upper Dir',
  'Lower Dir',
  'Malakand',
  'Bajaur',
  'Mohmand',
  'Khyber',
  'Orakzai',
  'Kurram',
  'North Waziristan',
  'South Waziristan',
  // Balochistan
  'Quetta',
  'Turbat',
  'Khuzdar',
  'Chaman',
  'Hub',
  'Sibi',
  'Loralai',
  'Dera Murad Jamali',
  'Zhob',
  'Gwadar',
  'Dera Allah Yar',
  'Usta Muhammad',
  'Sohbatpur',
  'Surab',
  'Pishin',
  'Killa Abdullah',
  'Killa Saifullah',
  'Mastung',
  'Kalat',
  'Nushki',
  'Washuk',
  'Kharan',
  'Chagai',
  'Nushki',
  'Panjgur',
  'Turbat',
  'Gwadar',
  'Lasbela',
  'Khuzdar',
  'Awaran',
  'Kech',
  'Panjgur',
  'Gwadar',
  'Ormara',
  'Pasni',
  'Jiwani',
  // Gilgit-Baltistan
  'Gilgit',
  'Skardu',
  'Chilas',
  'Ghanche',
  'Astore',
  'Diamer',
  'Ghizer',
  'Hunza',
  'Nagar',
  'Kharmang',
  'Shigar',
  // Azad Jammu and Kashmir
  'Muzaffarabad',
  'Mirpur',
  'Kotli',
  'Bhimber',
  'Rawalakot',
  'Bagh',
  'Hattian',
  'Neelum',
  'Haveli',
  'Sudhnuti',
  // Islamabad Capital Territory
  'Islamabad',
  'Rawalpindi',
]

// Sort cities alphabetically
export const sortedPakistanCities = [...new Set(pakistanCities)].sort()

